# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import robot_call_pb2 as robot__call__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in robot_call_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotCallStub(object):
    """Defines Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendInstructions = channel.unary_unary(
                '/robot_call.RobotCall/SendInstructions',
                request_serializer=robot__call__pb2.RobotCalling.SerializeToString,
                response_deserializer=robot__call__pb2.Response.FromString,
                _registered_method=True)


class RobotCallServicer(object):
    """Defines Service
    """

    def SendInstructions(self, request, context):
        """RPC to send a command to the robot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendInstructions': grpc.unary_unary_rpc_method_handler(
                    servicer.SendInstructions,
                    request_deserializer=robot__call__pb2.RobotCalling.FromString,
                    response_serializer=robot__call__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_call.RobotCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot_call.RobotCall', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotCall(object):
    """Defines Service
    """

    @staticmethod
    def SendInstructions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_call.RobotCall/SendInstructions',
            robot__call__pb2.RobotCalling.SerializeToString,
            robot__call__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
