# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot_call.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'robot_call.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10robot_call.proto\x12\nrobot_call\"\xf9\x02\n\x0cRobotCalling\x12\x1b\n\x13shoulder_pitch_left\x18\x01 \x01(\x02\x12\x1c\n\x14shoulder_pitch_right\x18\x02 \x01(\x02\x12\x12\n\nbicep_left\x18\x03 \x01(\x02\x12\x13\n\x0b\x62icep_right\x18\x04 \x01(\x02\x12\x1a\n\x12shoulder_roll_left\x18\x05 \x01(\x02\x12\x1b\n\x13shoulder_roll_right\x18\x06 \x01(\x02\x12\x19\n\x11\x66orearm_roll_left\x18\x07 \x01(\x02\x12\x1a\n\x12\x66orearm_roll_right\x18\x08 \x01(\x02\x12\x1a\n\x12wrist_flexion_left\x18\t \x01(\x02\x12\x1b\n\x13wrist_flexion_right\x18\n \x01(\x02\x12\x16\n\x0ewrist_yaw_left\x18\x0b \x01(\x02\x12\x17\n\x0fwrist_yaw_right\x18\x0c \x01(\x02\x12\x14\n\x0cgripper_left\x18\r \x01(\x02\x12\x15\n\rgripper_right\x18\x0e \x01(\x02\"0\n\x08Response\x12\x13\n\x0btransmitted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2O\n\tRobotCall\x12\x42\n\x10SendInstructions\x12\x18.robot_call.RobotCalling\x1a\x14.robot_call.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_call_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTCALLING']._serialized_start=33
  _globals['_ROBOTCALLING']._serialized_end=410
  _globals['_RESPONSE']._serialized_start=412
  _globals['_RESPONSE']._serialized_end=460
  _globals['_ROBOTCALL']._serialized_start=462
  _globals['_ROBOTCALL']._serialized_end=541
# @@protoc_insertion_point(module_scope)
