name: potato2
services:
    ros:
        build:
          ./.
        stdin_open: true
        tty: true
        network_mode: host
        platform: linux/arm64/v8
        devices:
            - /dev/dri/
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - $HOME/.Xauthority:/root/.Xauthority:ro
            - ./:/workspace
              #image: arm64v8/ros:humble
          #        entrypoint:
  #          - "/ros_entrypoint.sh"
  #      command:
  #        - "/bin/sleep infinity"
